### ISSUE TITLE
Fix Geo-Location API

### ISSUE THREAD

**Issue by thesauravkarmakar** [Aagam-Jain-113/AidZee#13]
After we click the **Public Room** Button, we should get Location Access popup. In the console, it should return the location's latitude or longitude and, if possible, instead of that, the exact location name.

**Comment by saurabhshalu** [comment]
Please mark this repo as hacktoberfest.

**Comment by thesauravkarmakar** [comment]
> Please mark this repo as hacktoberfest.

@saurabhshalu, do you want to solve this issue?

**Comment by saurabhshalu** [comment]
> > Please mark this repo as hacktoberfest.
> 
> @saurabhshalu, do you want to solve this issue?

I'll try my best to fix that issue sir! :)) Please assign me the issue.

**Comment by thesauravkarmakar** [comment]
> > > Please mark this repo as hacktoberfest.
> > 
> > 
> > @saurabhshalu, do you want to solve this issue?
> 
> I'll try my best to fix that issue sir! :)) Please assign me the issue.

Okay! I will assign it to you!

**Comment by thesauravkarmakar** [comment]
@saurabhshalu Do you want to work on more issues?

**Comment by saurabhshalu** [comment]
> @saurabhshalu Do you want to work on more issues?

Kindly merge the pull request. I have solved the previous issue.

You can open issues, and if I get time from my study I'll consider to work on them 👍

**Comment by thesauravkarmakar** [comment]
> > @saurabhshalu Do you want to work on more issues?
> 
> Kindly merge the pull request. I have solved the previous issue.
> 
> You can open issues, and if I get time from my study I'll consider to work on them 👍

Merged the PR #16
