### ISSUE TITLE
Add Loader 

### ISSUE THREAD

**Issue by thesauravkarmakar** [Aagam-Jain-113/AidZee#17]
After we click the **Public Room Button**, we should get Location Access popup, until the person _Allows it_ there should we a Loader something like this https://codepen.io/dctdevelop/pen/WbqbLb. After it is allowed then the page should open.

**Comment by saurabhshalu** [comment]
Kindly add **hacktoberfest** topic to the project too. It's only hactoberfest2020 is mentioned. Due to that I lost my 1 PR> :(

If you fix that, I'll work on this issue too.

**Comment by thesauravkarmakar** [comment]
> Kindly add **hacktoberfest** topic to the project too. It's only hactoberfest2020 is mentioned. Due to that I lost my 1 PR> :(
> 
> If you fix that, I'll work on this issue too.

I have done that. Please look into that! 

![image](https://user-images.githubusercontent.com/48858582/95014737-7e47d600-0666-11eb-9fe1-f65e9e858fb5.png)

**Comment by saurabhshalu** [comment]
You can assign me to this task. I'll try to improve it.

What screen you want if user denied to give the location access? 

Just the console log will be fine as it was in my last PR?

**Comment by thesauravkarmakar** [comment]
You can give some Pop-Up Error showing 'Until Location Access isn't given he/she can't move to Public Room.' 

Assigning to you, @saurabhshalu

**Comment by thesauravkarmakar** [comment]
Solved #19
